[package]
name = "doppler_indexer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "1.5.2", features = ["serde"] }
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
